### ISSUE TITLE
res.write is not a function

### ISSUE THREAD

**Issue by hshine1226** [bikk-uk/jest-mock-express#68]
``` ts
 expect(res.write).toBeCalled() // TypeError: res.write is not a function
```

**Comment by aboyce** [comment]
This looks like it comes from me not diving deep enough into the `Response` to ensure everything is there.

I've created new issues to fully add in the properties and functions for:
- #73
- #72

Thanks for raising the issue 👍 I'll track the work against those two tickets (they are linked now so you can get updates) as I'd rather implement all the missing properties in one rather than patching in certain ones. It will also have to be done after the next major release otherwise merging it all back in will be problematic. Apologies for the delay caused by this.
